---
version: "3.9"
services:
  sui-full-node:
    image: mysten/sui-rosetta-testnet
    ports:
      - "9000:9000"
    expose:
      - "9000"
    working_dir: /sui/testnet
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/sui-node --config-path fullnode.yaml
    stdin_open: true
    tty: true
  rosetta-online:
    image: mysten/sui-rosetta-testnet
    ports:
      - "9002:9002"
    expose:
      - "9002"
    working_dir: /sui/testnet
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/sui-rosetta generate-rosetta-cli-config --env testnet &
        /usr/local/bin/sui-rosetta start-online-remote-server --env testnet --full-node-url http://sui-full-node:9000
    stdin_open: true
    tty: true
  rosetta-offline:
    image: mysten/sui-rosetta-testnet
    ports:
      - "9003:9003"
    expose:
      - "9003"
    working_dir: /sui/testnet
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/sui-rosetta start-offline-server --env testnet
    stdin_open: true
    tty: true

